brave/leo

package.json

Introduces `install` script until we decide if we're publishing to npm or not

Allow dependent projects via npm to access build output

---

.storybook/global.svelte
examples/example-ui-react/src/App.tsx
tests/cssOutput.test.ts
tokens/config.js
tokens/legacy-colors.json

Adds colors from the pre-leo design system, since apparently they're still being used in new figma designs. Developers have an active need to use these variables, so we'll include them. But, to make sure developers don't use them just because the colors match, or at least know they are not intended to be used forever, we'll use the `"legacy"` prefix.
Output example:
```css
--color-legacy-text1: rgb(33, 37, 41);
--color-legacy-light-mode-text1: rgb(33, 37, 41);
--color-legacy-dark-mode-text1: rgb(0, 0, 0);
@media (prefers-color-scheme: light) {
--color-legacy-text1: rgb(0, 0, 0);
}
```

Legacy colors

---

tokens/transformation/tailwind/formatCssColorVars.js
tokens/transformation/web/formatCss.js

Fixes #33
This reduces the generate size of `css/variables.css` by ~12% and of `tailwind/variables.css` by ~15%

Remove redundant declarations

---

.gitignore
package.json
scripts/common.js
scripts/gen-react-bindings.js
scripts/gen-svelte-types.js
web-components/button/react.ts

This is based on the `genprops` script. In addition, this PR removes the generated files from the repository and regenerates them as part of the `build` script.

Add script for generating React bindings

---

package-lock.json
package.json
web-components/button/button.stories.svelte
web-components/button/button.svelte

This does the following:
1) Makes it possible to passing through button attributes.
2) Updates the type definitions such that the button is either a button or a link.
3) Adds the type definitions for the Button/A tag as optional props.
It does not:
1) Add support for events.
@petemill what do you think about this as an approach?

Improve Button type definitions

---

package.json

Installing in another project was returning an error due to a this package missing.

moves svelte2tsx to prod dep

---

tokens/transformation/skia/index.js
tokens/transformation/skia/templates/colors.h.template

The Skia generation was broken (the output file was empty). I think this happened when we added support for Legacy colors and changed `DarkMode`/`LightMode` to `Dark`/`Light`.
(also adds a trailing `;` & fixes the namespaces).
<details>
<summary>Example Output</summary>
```cpp
// Copyright (c) 2022 The Brave Authors. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// you can obtain one at http://mozilla.org/MPL/2.0/.
#include "third_party/skia/include/core/SkColor.h"
namespace leo::light {
constexpr SkColor kColorTextPrimary = SkColorSetRGB(0x1D,0x1F,0x25);
constexpr SkColor kColorTextSecondary = SkColorSetRGB(0x6B,0x70,0x84);
constexpr SkColor kColorTextInteractive = …
```

Fix the Skia generation

---

examples/example-ui-react/src/App.tsx
scripts/gen-react-bindings.js
web-components/button/button.svelte
web-components/svelte-react.ts

This is an alternative to #135, which gets generic type definitions working nicely with React. Made in response to https://github.com/brave/leo/pull/135#issuecomment-1352355559

Fix React bindings when we have generic arguments

---

.github/workflows/build.yml
package.json
web-components/button/button.svelte
web-components/navdots/navdots.svelte

I merged the `svelte-check` PR here but the new `svelte-check` is a bit stricter and I noticed it was complaining about some previously valid code.
In addition, I'm running `svelte-check` as part of CI, so we'll catch regressions. In future, it'd be good to enable the `--fail-on-warnings` flag but at the moment there's no way of whitelisting our `@theme` at rule

Fix `svelte-check` errors and add check to CI

---

package-lock.json
package.json
scripts/gen-react-bindings.js
todo.md
web-components/navdots/navdots.stories.svelte
web-components/navdots/navdots.svelte
web-components/svelte-react.ts

This isn't 100% complete but is pretty useful as-is. Our major blockers are:
1. Patch Svelte to not break out CSP https://github.com/sveltejs/svelte/pull/8135
2. Work out some strategy for compiling Leo for consumers which aren't already using Svelte. Current dependencies Leo adds to brave-core:
1. @brave/leo
2. css-tree
3. svelte
4. postcss
5. svelte-loader
6. svelte-preprocess
which seems somewhat excessive.

Changes to Leo to make it more usable from Brave Core

---

CODEOWNERS

This is in preparation of adding Leo as a brave-core dependency in https://github.com/brave/brave-core/pull/16787
On @kdenhartog's recommendation I've just added @petemill, @AlanBreck and myself as owners. Happy to add anyone else who seems sensible.

Add CODEOWNERS as part of security review

---

.github/renovate.json

We want them to be as permissive as possible, rather than forcing all consumers of Leo to be up to date (even though that would be ideal.
See here for source:
https://github.com/renovatebot/renovate/issues/323#issuecomment-629139930

Don't rennovate peerDependencies

---

.github/workflows/build.yml

This allows us to avoid running install scripts, like [this one from `core-js-pure`](https://github.com/brave/leo/pull/181#issuecomment-1405099072).
This protects us [against some supply chain attacks](https://dev.to/naugtur/get-safe-and-remain-productive-with-can-i-ignore-scripts-2ddc). We can periodically use [can-i-ignore-scripts](https://www.npmjs.com/package/can-i-ignore-scripts) to determine if we need to allow any more by including in the `npm build ...` line.

Ignore install scripts for npm packages

---

examples/example-ui-react/public/index.html
examples/example-ui-react/src/App.tsx
src/components/svelte-react.ts

This makes it possible to add a whitelisted set of HTMLElement props to the WebComponent. This will allow us to style Leo components with `styled-components` and set common properties, like `style`, `id` and `className` on our Leo components.
It will enable styling like the following:
```ts
import styled from 'styled-components'
import Navdots from '@brave/leo/react/navdots'
const StylishDots = styled(Navdots)`
--leo-navdots-active-color: hotpink;
margin-top: 100000px;
`
```

HTMLElement Props Support

---

.github/workflows/build.yml

I messed up a merge and the `format` section was present twice, causing the builds to not run.

Fix broken build

---

.storybook/argHelper.ts
src/components/label/label.stories.svelte
src/components/progress/progressBar.stories.svelte
src/components/progress/progressBar.svelte
src/components/progress/progressRing.stories.svelte
src/components/progress/progressRing.svelte

Fixes https://github.com/brave/leo/issues/202
- Makes the progress ring resizable (while maintaining the ability to set the stroke width & and CSS variables)
- Split the `progress` story into a `progressRing` and `progressBar` story
- Update the stories to list out the CSS variables
- Type the mode, so it's obvious what the options are

Progress Improvements

---

package-lock.json
package.json
src/scripts/gen-react-bindings.js
src/scripts/gen-svelte-types.js
tests/theme.common.js

- Fixes breaking change from `svelte2tsx` bump which changed the output folder of the type definitions
- Remove `jest` from `package.json` as we're using `ts-jest`
- Move `ts-jest` from 'dependencies` to `devDependencies`
- Fix broken import in test

Fix build & tests

---

package-lock.json
package.json

We have multiple dependapot alerts due to an [outdated version of axios which `figma-js` depends upon](https://github.com/jemgold/figma-js/blob/main/package.json#L57).
I thought about submitting a PR to the `figma-js` project, but got errors as soon as I tried `npm install` due to conflicts with `tslint`, which has apparently been deprecated since 2019.
This seems to be the path of least resistance.

forces resolution for axios

---

src/tokens/transformation/common/leoParser.js

Strips out "⚙️" from "⚙️ Components". I did a diff of variables.css and it's unchanged.

strip more emoji from token names

---

src/scripts/gen-react-bindings.js

Previously, we had no type definitions for module exports, even though we were exporting them from the WebComponents. This meant I couldn't call `setIconsBasePath` in Brave Core

Add type definitions for context='module' exports

---

src/tokens/config.js
src/tokens/transformation/skia/templates/colors.h.template

Questions:
~1. Should I be doing substitution to make the dark colors automatically work (i.e. `kColorPrimary40` is `primary40` in light and `primary60` in dark).~ This is handled in Figma
2. Should I depend on the Chromium `PreferredColorScheme` type instead of introducing `leo::Theme::{kDark,kLight}`

Improves Skia output to make it easier to use in Brave Core

---

.storybook/main.cjs
rollup.config.js
src/postcss/theme.js
tests/theme.mixed.test.js

Fixes https://github.com/brave/leo/issues/230
This fixes the styles for `<leo-toggle>` and `<leo-button>`. However, I think it will only solve the problem for a single level of nesting.

Fix bug in WebComponent @theme

---

package-lock.json
package.json

Once we upgrade Leo consumers we should be able to delete our fork.
https://github.com/sveltejs/svelte/issues/8134#issuecomment-1463047453

[Dependencies]: Point to upstream Svelte

---

src/components/button/button.svelte

Allowing it to grow inline by default, or be stretched to a specific width via flexbox or a specific width, etc

The Button, when used as a web component, should be inline-block by default

---

.storybook/main.cjs
examples/plain-html/index.html
package.json
rollup.config.js
src/components/button/button.svelte
src/components/collapse/collapse.svelte
src/components/icon/icon.svelte
src/components/label/label.svelte
src/components/link/link.svelte
src/components/navdots/navdots.svelte
src/components/progress/progressBar.svelte
src/components/progress/progressRing.svelte
src/components/svelte-react.ts
src/components/svelte-web.ts
src/components/toggle/toggle.svelte
src/postcss/theme.js
src/scripts/gen-react-bindings.js
src/scripts/gen-web-bindings.js
tests/theme.mixed.test.js

Fix https://github.com/brave/leo/issues/245
Fix https://github.com/brave/leo/issues/244
Unfortunately, this means we need to write our own wrapper. On the bright side, Svelte's web components are **not** well supported and have a number of bugs including:
- Nested component slots conflict with parent component slots
- Nested components styles are not applied
This means we have a bit more room to fix bugs / make changes to how things work. On the other hand, this might make life harder if Svelte changes things down the tracks. We do get a few wins from this:
1. I suspect we'll have a smaller bundle size because more code is shared
2. We can turn child slots on & off! (in Svelte an `{#if false}` is treated as slotted content).
3. We can use advanced Svelte behavior (like bind) inside Leo, …

Svelte doesn't allow Web Components which contain Svelte components.

---

.github/renovate.json

It appears from [the Renovate docs](https://docs.renovatebot.com/configuration-options/#schedule) that the `schedule` config expects an array.

updates renovate schedule config

---

examples/example-ui-react/src/App.tsx
src/components/button/button.stories.svelte
src/components/button/button.svelte
src/components/button/props.ts

- Adds `jumbo` Size
- Adds `tiny` size
- Adds `plain-faint` variant
- Rename existing variants to match Figma
- `primary` ==> `filled`
- `secondary` ==> `outline`
- `tertiary` ==> `plain`
FWIW, I need the `jumbo` size for https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=3641-72342&t=SemMRN4c5wM7TB9p-0 and the `plain-faint` kind

[Button]: Add new button variants

---

src/components/button/button.svelte
src/components/collapse/collapse.svelte
src/components/link/link.svelte
src/components/navdots/navdots.svelte
src/components/toggle/toggle.svelte

Currently on mobile, tapping anything with `cursor: pointer` will result in a nasty blue rectangle on WebKit/Chromium browsers. The solution is to just set `-webkit-tap-highlight-color: transparent` when we set `cursor: pointer`.
Before:
After

[Bug]: Fix mobile tap highlights

---

src/components/svelte-react.ts

The `ref` is null when the component is being unmounted, which was causing us to log a bunch of incorrect error messages

[React]: Remove incorrect warning

---

src/components/icon/icon.svelte
src/scripts/gen-skia-icons.js

This fixes a few bugs in the icon:
1. The `iconBasePath` is changed after the `Icon` is mounted, which wouldn't trigger a rerender
2. The icon changes from `color` to `non-color`, or vice versa, and the icon wouldn't detect the change.
3. Centre non-square icons (like the flags) so they don't look off

[Icons]: Fix for reactivity bugs

---

src/components/svelte-web.ts

Interestingly, something Polymer does internally triggers the web component to be reattached to the node. This was the original cause of my issues with the sidebar, and seems to affect Leo too. Fortunately the fix from the Leo end is easy.

[Web Components]: Fix bug where polymer would sometimes remount component

---

examples/plain-html/index.html
src/components/toggle/toggle.stories.svelte
src/components/toggle/toggle.svelte

Rename the `on` property on `Toggle` to `checked` as it was conflicting with the event handling type definitions. In future we shouldn't include any properties named `on` or starting with `on` :facepalm:

[Components]: Toggle `on` ==> `checked`

---

src/scripts/icons/skiafy.js

For example, this fixes the `pwa-install` Skia Icon, making it look like this:
Instead of
This should unblock https://github.com/brave/brave-core/pull/18339
I made this when I was trying to work out what was going on, which I found quite useful:
https://github.com/fallaciousreasoning/skia-icon-editor
https://skia-icon-editor.vercel.app/

Fix bug in Skiafy for paths starting with a relative command

---

src/components/checkbox/checkbox.stories.svelte
src/components/checkbox/checkbox.svelte
src/components/radioButton/radioButton.stories.svelte
src/components/radioButton/radioButton.svelte

This fixes (partially) https://github.com/brave/leo/issues/261, by making it possible to reverse the direction of the label/checkbox. However, we should definitely think about this some more.
This fixes the issue raised here: https://bravesoftware.slack.com/archives/C03A0MWJXP0/p1681934571717649

Make it possible to change the direction of radios/checks

---

examples/example-ui-react/src/App.tsx
src/components/dropdown/dropdown.svelte

1. Define `leo-option` element for use in Dropdown. This makes it possible to set from React
2. Remove `aria-selected` attribute - the web component was not regenerating these every change, like Svelte does
3. Disable pointer-events on the button - there was a weird Chromium only bug (which I think is just in Nightly) where it was triggering a double pointer event. It worked (and still works) fine in Firefox.

[Dropdown]: Fixes for use in React

---

src/tokens/transformation/skia/templates/colors.h.template

`enum class`'s member should be scoped with the name of `enum class`
fix https://github.com/brave/leo/issues/290

Prefix enum class name before each cases

---

src/components/alert/alert.svelte
src/components/collapse/collapse.svelte
src/components/dropdown/dropdown.svelte
src/components/label/label.svelte
src/components/navdots/navdots.svelte
src/components/progress/progressBar.svelte
src/components/progress/progressRing.svelte
src/components/toggle/toggle.svelte

By default, custom elements are `display: inline` which is (most of the time) not what is expected. I just ran into this trying to size the `<Alert>` component in React so I thought I'd go through and add my best guess of what should be what. Happy to change anything.

[Meta] Add `display` property to the CSS for custom elements

---

src/components/alert/alert.svelte
src/components/collapse/collapse.svelte
src/components/dialog/dialog.svelte
src/tokens/browser.tokens.json
src/tokens/universal.tokens.json

- Updated secondary styles
- **BREAKING:** Created secondary heading styles
This change is breaking, as it renames the `--leo-font-heading-*` tokens to `--leo-font-primary-heading-*`
- Updated browser color values

[Breaking Change]: Tokens update

---

src/components/dropdown/dropdown.svelte
src/svelteDirectives/clickOutside.ts

Fixes https://github.com/brave/leo/issues/302
Fixes https://github.com/brave/leo/issues/305
- Add optional key attribute, so the component can be used from a list
- Fix bug where the empty string was treated as 'no-value', causing the placeholder to be rendered.
- Adds a better default value renderer (renders the `.textContent` of the selected option)

[Dropdown]: Minor fixes, to make React use easier

---

src/tokens/transformation/web/formatCssAsJs.js
tests/tokens.js.test.js

Currently, the JS tokens don't exactly match up with the CSS variables. For example, the `desktop` portion of the CSS variables is stripped but not in the tokens. This leads to some JS tokens which don't exist. For example:
`font.desktop.primary.heading.h3: var(--leo-desktop-primary-heading-h3)`, which does not exist. This should be `font.primary.heading.h3: var(--leo-primary-heading-h3)`.
Additionally, this adds a test, so we'll know if we break this again.

Fix JS tokens

---

package.json
src/scripts/audit-tokens.js
src/scripts/common.js

Fixes https://github.com/brave/leo/issues/309
We've had some issues with names of tokens changing, and until this PR, there's been no easy way for us to check whether any of the changed variables are used in other projects.
The script adds a simple command which checks all `--leo-` variables are defined in the Leo repository.

[Meta]: Adds a script for auditing tokens

---

src/scripts/audit-tokens.js

I added a node_modules ignore, and it was working when I was installing the module from a folder. Obviously it broke when I installed Leo via Github (and into node_modules) :facepalm:

[Audit]: Fix bug where I was ignoring component tokens

---

src/components/button/button.svelte

Resolves https://github.com/brave/leo/issues/318
All button variants now have a constant border radius that is half of the button's height.

Modified border radius all button variants

---

src/components/collapse/collapse.svelte

Svelte was compiling the `SVG` element to an `innerHTML` assignment. Unfortunately, this broke brave-core's TrustedTypes policy. The fix was just to not use an inline SVG.

[Collapse]: Remove SVG which was breaking TrustedTypes assignment

---

icons/meta.d.ts
icons/meta.js
src/scripts/update-icons.js

The current icons meta exports the type as the default export. This means you can't use the icon names, just the type (which doesn't exist at runtime).

[Icons]: Update type definitions for icons

---

src/scripts/audit-tokens.js

Windows uses a different path separator (`\\`), so obviously this wasn't ignoring `node_modules`....

[Audit]: Don't include node_modules on Windows

---

src/components/icon/icon.svelte

This fixes a bug where a request would get made to the default icon url before we'd had a chance to set the icon base path, resulting in 404s.

[Icons]: Only preload icons when idle

---

src/scripts/audit-tokens.js
src/scripts/common.js

On windows CI, we're getting into a loop when walking directories, due to recursive hard symlinks. Fortunately, the symlinks are in `node_modules` which we're (mostly) filtering out anyway.
I've updated the walk function to not walk ignored folders, rather than just ignoring entries from ignored folders. This makes the script nearly instant too!

[Audit]: Don't walk ignored folders

---

src/tokens/transformation/skia/templates/colors.h.template
src/tokens/transformation/skia/templates/radius.h.template
src/tokens/transformation/skia/templates/spacing.h.template

Fix #340
Usually we use #ifndef template, but generated resources seems to be okay with #pragma once. Actually, the path could be different on the client source code, `pragma once` makes sense.

Add #pragma once for header files

---

src/components/button/button.svelte

This adds explicit styling for the `:visited` state in order to avoid having styles from `link` apply when the `button` component is an `<a>` tag instead of a `<button>`.

adds explicit :visited style to button component to avoid conflicts with anchor styles

---

examples/example-ui-react/src/App.tsx
src/components/input/input.svelte

This fixes two issues:
1. Type definitions weren't optional for optional fields :facepalm: 
2. Events weren't typed properly (i.e. `event.target` was being typed as `EventTarget` which made it super unpleasant to use).

[Input]: React cleanup

---

src/components/buttonMenu/buttonMenu.stories.svelte
src/components/menu/menu.svelte

Menu Item enhancements:
- Styling matches figma (hover, selection, focus)
- Pressing enter on the items actually clicks them
- Items can opt out of built-in styles and tabbing / keyboard down arrow and enter press via using a <div> (maybe it's separators or custom interactivity)
- Items can opt out of the menu immediately closing on selection by specifying `data-is-interactive={true}`

Menu item styles and interactivity

---

src/components/menu/menu.svelte

The `--leo-color-text-highlight` token does not exist - instead the Menu text color should not change on hover.
In addition, the Typechecking step was failing because the result of `querySelectorAll` is `Element[]` rather than `HTMLElement[]`.
**Note:** This is causing all builds to fail on `main`.

[Menu]: Remove highlight color

---

src/components/button/button.stories.svelte

Previously we weren't showing the variable in the storybook

[Storybook]: Add button padding to storybook

---

.github/workflows/build.yml

PRs like https://github.com/brave/leo/pull/383 don't have their CI steps run because they are not directly against `main`, but another branch. This fixes that.

CI: Run Deploy on all branches and not only "main"

---

src/components/dropdown/dropdown.svelte

1. Fix sizing: We were applying a padding we didn't need, which resulted in the Dropdown size being 50px instead of 44px
2. Fix focus outline: We were applying a focus outline to the click target resulting in a double focus ring
3. Fix keyboard selection: On selecting a menu item, the control was unfocused, and you couldn't reopen the component.

[Dropdown]: Fix dropdown bugs introduced during migration to Menu/Floating

---

examples/example-ui-react/src/App.tsx
src/components/buttonMenu/buttonMenu.stories.svelte
src/components/menu/menu.svelte

Fix https://github.com/brave/leo/issues/404
> Menu items should not call `element.click()` when clicked, only when using keyboard selection and pressing enter.

Menu: fix click getting fired twice when clicking menu items

---

src/components/alert/alertCenter.svelte

Currently, alert UI could be below other UI components. Sets the default z-index and makes a css variables to control the z-index

Set z-index for alert center

---

.github/workflows/build.yml
.github/workflows/deploy.yml

This PR addresses an issue preventing Preview Deployments for PRs from external forks.
The fix separates the `Build` and `Deploy` workflows (Deploy is triggered by `workflow_run`, ensuring the deployment runs in the default branch context and can access necessary secrets). 
see also:
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#accessing-secrets
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

CI: Separate Build/Deploy workflows

---

src/components/dropdown/dropdown.stories.svelte
src/components/dropdown/dropdown.svelte

Fixes https://github.com/brave/leo/issues/411
Adds error props to the drop down menu. I copied this pattern from the [Input](https://github.com/brave/leo/blob/main/src/components/input/input.svelte#L150) component.
Props:
- `hasErrors`
- `showErrors`
- Adds a slot for a custom error message
Screenshot from storybook:

[Dropdown]: Adds error slot using hasErrors and showErrors

---

src/components/formItem/formItem.svelte
src/components/input/input.svelte

- adds more support for default attributes on Input component
Currently, the input component doesn't support `type="email"`, this PR adds support for that and other input types which we may want to use.
- fixes background color on formControl and renames classes
The primary fix here is an incorrect CSS var, but I've additionally renamed the classes to follow suit with the Button component: `isFilled`, `isOutline`, etc. This is helpful especially in the context of projects that use the extracted component styles as Tailwind plugins since `outline` is a default class to style the `outline` property on interactive elements.

Input fixes

---

src/tokens/transformation/tailwind/extractComponentStyles.js
src/tokens/transformation/tailwind/static/plugins/index.ts

This makes it so that Tailwind component plugins (extracted from the Svelte components) can be imported individually into a project's Tailwind config instead of all at once.

splits tailwind component plugins into individual imports

---

.github/workflows/deploy.yml

Currently, the PR comment format is off due to indentation triggering Markdown quotation code block styling:

(ci): fixes formatting for preview links in PR comment post-deploy

---

examples/plain-html/index.html
src/components/button/button.stories.svelte
src/components/button/button.svelte
src/components/progress/progressRing.stories.svelte
src/components/progress/progressRing.svelte

This PR primarily deals with icons in buttons and the button loading state:
1. Adds `<ProgressRing>` as the loading icon for all buttons
a. Modifies the `<ProgressRing>` component to remove customization of the background ring color as per conversation with @aguscruiz.
b. Adds a non-linear easing function to `<ProgressRing>`'s indeterminate state.
3. Adds slots for `left-icon` and `right-icon` to button instead of relying on consumer to handle layout
4. Sets button to `disabled` if `isLoading` is true
Out of scope for this PR is adding a determine flag for the button loading icon. This bridge can be crossed when someone finds the need. :-)
**NOTE:** I'd recommend that this PR be `Rebased and merge`d instead of squashed as it has three distinct commits.

adds loading icon and icon slots to button

---

src/components/dropdown/dropdown.stories.svelte
src/components/dropdown/dropdown.svelte
src/components/input/input.stories.svelte
src/components/input/input.svelte

Resolves https://github.com/brave/leo/issues/455
Currently to show error messages on inputs, `hasErrors` prop is passed. This uses `$$slots.errors` instead of exposing the `hasErrors` prop, implemented on `Dropdown` and `Input` components.
Dropdown:
Input:
Dropdown:
Input:

Detect error slot for inputs instead of hasErrors prop

---

src/components/floating/floating.svelte
src/components/tooltip/tooltip.svelte

Resolves https://github.com/brave/leo/issues/444
Right now tooltips on default mode don't show an arrow. This PR adds an arrow and solves an issue with the tooltip disappearing when trying to interact with the content (such as a button).
https://github.com/brave/leo/assets/5668789/5c9048f7-9489-4ea2-8adf-00bc1ee8be55
https://github.com/brave/leo/assets/5668789/ccf18a7f-0045-49ab-a145-90434825aef4

[Tooltip]: adds arrow on tooltip default mode

---

src/components/floating/floating.svelte
src/components/tooltip/tooltip.svelte

Right now in main, if you hover over a tooltip and hover out a few times, the arrow positioning sometimes computes incorrectly. This fixes it by validating arrow positioning before firing the `computedposition` event on the `Floating` element.
This PR also adds a few other things discussed with @fallaciousreasoning, a prop named `mouseleaveTimeout` for the debounce timeout on the mouse leave event, and defaults to no fadeout animation on the tooltip, with a prop named `fadeDuration` to set it if desired.
https://github.com/brave/leo/assets/5668789/db216dc8-16eb-48cf-bd8e-6256dea8656c
https://github.com/brave/leo/assets/5668789/9d1c07d5-8694-4436-a6f2-56845b6507ef
https://github.com/brave/leo/assets/5668789/d071c71b-5bbc-4d00-8243-8bd8a425039d

[Tooltip]: Validates arrow positioning / adds timeout props

---

src/components/floating/floating.svelte

Sometimes the arrow event is `undefined` which causes a crash
Additionally, we were early returning from the `computePosition` function if the arrow data was bad, meaning the tooltip wouldn't get positioned!

[Tooltip]: Fix positioning error

---

src/components/button/button.svelte
src/components/checkbox/checkbox.svelte
src/components/collapse/collapse.svelte
src/components/dialog/dialog.svelte
src/components/dropdown/dropdown.svelte
src/components/radioButton/radioButton.svelte
src/components/svelte-react.ts
src/components/toggle/toggle.svelte
src/components/tooltip/tooltip.svelte
src/scripts/gen-react-bindings.js

Resolves https://github.com/brave/leo/issues/407
For react components, currently  generic typing allows any event prop to be used (e.g. `<LeoButton onClick={...}>`), if an incorrect event name is used (e.g. `<LeoButton onClicked={...}>`) there is no type error. Ideally a type error for an incorrect prop name would show.
This solves this by generating an event type for the react components by parsing the corresponding svelte type file, it should contain event types resulting from the typed `createEventDispatcher`. When there are no events defined in the svelte file it doesn't include any event types.
For example, in [input.svelte#L74-L84](https://github.com/brave/leo/blob/7a65a548c3c801fcdf8b86a98118a758bfa004c8/src/components/input/input.svelte#L74-L84):
```ts
type InputEventDetail = { …
```

[Component]: adds event types to react

---

src/scripts/gen-react-bindings.js

Not sure why this wasn't breaking Linux/MacOS but it wasn't

[Events]: Fix event type generation on Windows

---

src/scripts/gen-react-bindings.js

The old event regex was only matching types defined in place (i.e. `{ foo: number }`), so was breaking for `undefined`, `any` and `never`.
This seems to have been triggered by the Svelte4 upgrade (previously, undefined event types would be `{}` but now they're either `undefined` or `any`).

[Events]: Fix regex for extracting event types

---

src/components/tooltip/tooltip.svelte

Fixes an unhandled error caused by deleting the `middlewareData.arrow` property in the floating component.
Fixes this issue:
https://github.com/brave/leo/assets/5668789/9f9088ec-c12f-45e7-8764-38220fa502c7
@fallaciousreasoning This was caused by https://github.com/brave/leo/pull/469, and in this PR I'm assuming returning early is ok in the tooltip here (it doesn't seem to cause any other bugs).

[Tooltip]: Fix unhandled error in positionArrow

---

src/components/tooltip/tooltip.svelte

Closes https://github.com/brave/leo/issues/477
When the content inside the tooltip is without a defined width, such as when it is text content, there is a scroll effect as the `floating-ui` library computes the max content width - only when along an edge of the browser. Adding `width: max-content;` fixes it for when the tooltip content is just text.
https://github.com/brave/leo/assets/5668789/453d9630-a15b-4d7a-9a38-f91beaaa73ba
https://github.com/brave/leo/assets/5668789/d54e5348-623e-4ca4-b24a-61e1b7beab51

[Tooltip]: Fix scroll on screen using width: max-content css prop

---

src/components/menu/menu.svelte

Part of https://github.com/brave/leo/issues/391
On the menu there is a scroll effect as the `floating-ui` library computes the max content width. Adding `width: max-content;` fixes this issue, this is mentioned in the docs here: https://floating-ui.com/docs/computePosition#initial-layout
I found this solution while fixing https://github.com/brave/leo/pull/477 which is the same problem just manifested a bit differently.
https://github.com/brave/leo/assets/5668789/b163ae59-2139-48b3-bcaf-2cae6d2c43a5
https://github.com/brave/leo/assets/5668789/f0252160-0c62-473a-9f01-7f9edcc1638c

[Menu]: Fix scroll on screen using width: max-content css prop

---

src/components/menu/menu.svelte

closes https://github.com/brave/leo/issues/391
Uses the [floating ui size middleware](https://floating-ui.com/docs/size) to keep menus from overflowing the scroll container.
https://github.com/brave/leo/assets/5668789/e937e68c-ac1c-4a83-8ef9-52979ec8d5cc
https://github.com/brave/leo/assets/5668789/b3453112-bd36-4ab1-9378-8a960f94bc1a
https://github.com/brave/leo/assets/5668789/b684a6e4-a992-4845-8c54-a50d3d504be7
https://github.com/brave/leo/assets/5668789/b798aff6-8bde-4a27-aea3-09443ada1d82

[Menu] Adds size middleware

---

src/components/input/input.svelte

Removes unused import of `ChangeEventHandler`, noticed it in my linter.

[Input]: Remove unused import

---

src/postcss/theme.js

There were a couple of problems:
1. The `wrapSelector` wasn't being used for the `prefers-color-scheme` media query
2. With `wrapSelector` the specificity was too high, and the media query was overriding the `[data-theme]` selectors

@theme plugin fixes

---

package-lock.json
package.json
src/components/svelte-react.ts
src/scripts/gen-react-bindings.js

For `Button` the ref type was evaluating to `never` which wasn't ideal

[Types]: Fix ref type definitions

---

src/components/input/input.svelte

This fixes the issue where react/web component consumers can't set the placeholder text.

[Input]: Add an explicit placeholder

---

src/components/svelte-web.ts

This delegates the focus to the first focusable element (or the element with `autofocus`) inside the shadowDOM when `.focus()` is called on the element.
I don't know if we want this for every component, but it does seem like a sensible default.
https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/delegatesFocus

[Focus]: Set delegatesFocus on all components

---

src/components/navdots/navdots.svelte
src/components/toggle/toggle.svelte

Currently, the Navdots and Toggle do some calculations with CSS properties which don't play nice with RTL. This fixes them.

Add RTL support in Toggle and NavDots

---

src/components/formItem/formItem.svelte

@aguscruiz could you take a look at this? For the Brave News stuff, I need to be able to customize the color of the `Input` control. To do this, I have to define the hover/background/border colors in terms of `--leo-control-color` mixed with the foreground/background color.
The colors are **slightly** different to what was there originally, so mind taking a look (and setting `--leo-control-color`). Looks nicest with colors which have some transparency (try `rgba(255,0,0,0.4)`).

[FormItem]: Make it possible to customise control colors

---

src/components/alert/alert.stories.svelte
src/components/alert/alertCenter.svelte
src/components/button/button.stories.svelte
src/components/buttonMenu/buttonMenu.svelte
src/components/dialog/dialog.stories.svelte
src/components/dialog/dialog.svelte
src/components/dialog/dialogsContainer.svelte
src/components/input/input.svelte
src/components/navdots/navdots.stories.svelte
src/scripts/audit-events.js
src/scripts/common.js

Followup to #600 
I missed some internal usages of the old style events (which obviously Typescript doesn't catch because svelte is fine with any `on:` events being added to components.
Wrote a script to find accidental usages and added it to presubmit.

[Svelte]: Fix missed events

---

.storybook/main.ts

While not perfect (mainly referring to the `Source code` view not working properly), I think docs are a helpful way to quickly survey the component stories, and to easily surface/link to the props.

Enable autodocs for Storybook

---

examples/example-ui-react/src/App.tsx
src/components/formItem/formItem.svelte

From [a little peaking online](https://github.com/w3c/csswg-drafts/issues/6867), it doesn't seem as though it's entirely possible yet to select empty slots.
I'm also not sure it's entirely necessary since there's no slot added if the component has no children. I did, however, replace it with a selector which I believe accomplishes the intent of the other selector (an element passed as a child, but without content), and seems to work.

[FormItem]: fix bad selector inadvertently hiding label

---

src/components/svelte-web.ts

I didn't realise this was a thing you could do, but if you pass an object with a `handleEvent` function, that will be invoked!
This is what `LitElement` does, so we won't work with LitElement until we fix this.

[Events]: Allow event handler objects

---

src/components/tooltip/tooltip.svelte

The content of the `Tooltip` isn't immediately available, so don't show the tooltip until we have content.

[Tooltip]: Don't show tooltip unless there is content

---

src/components/checkbox/checkbox.svelte

Not sure how this passed type checking - I guess this passed typechecking because `e` has the any type.

[Checkbox]: Fix how handler is called

---

src/components/tooltip/tooltip.svelte

Currently we don't have any slots in the tooltip, so I didn't do the Button/gap padding adjustments.
Fixes #656

[Tooltip]: Update default padding

---

src/components/dropdown/dropdown.svelte
src/components/formItem/formItem.svelte
src/components/input/input.svelte

As is traditional, our fix for `FormItems` not rendering labels broke by making `FormItems` with no label render a label.
This passes through from the consumer whether a label has been set, which will hopefully put the issue to bed.

[FormItem]: Conditionally render label slot

---

src/components/button/button.svelte
src/scripts/gen-android-icons.js

- **[Meta]: removes console log in android icon generation**
- **[Button]: fix button height consistency**
- **[Button]: ensure proper padding when contents is only a text node**
This is important for Tailwind consumers since a class is applied to elements without necessarily wrapping contents in an element with `.content` as would happen when using as a JS component.

more button fixes

---

src/components/svelte-react.ts

This lets you set the `slot` attribute directly on Nala components

[React]: Add slot support

---

examples/example-ui-react/src/App.tsx
examples/example-ui-react/tsconfig.json
examples/example-ui-react/webpack.config.js
src/components/icon/icon.svelte
tsconfig.json

Consuming apps should know @brave/leo but ../../../ is not the correct relative path from the typescript build output path
I confirmed I didn't need to change anything for consuming apps to get the intellisense to work:

Ensure consuming apps receive Icon's IconName type instead of a bad relative import path

---

src/components/input/input.svelte

The opacity value was chosen because it looks pretty similar for our existing dark/light mode. This means if you override the text color, the placeholder color will fit right in.
Needed for the NTP Search project.

[Input]: Placeholder color should follow text color

---

src/tokens/transformation/tailwind/twShadows.js

Since Tailwind colors need to support user defined opacities, they they are set as partials instead of a full color function (e.g. `255, 255, 255` vs `rgba(255, 255, 255, 1)`). This caused a problem with shadows like "focus-state", though, since it was referencing a partial without being wrapped in a color function.

[Tokens](Tailwind): fixes color references in shadows

---

.storybook/global.svelte
src/tokens/browserFontTokens.stories.svelte
src/tokens/marketingFontTokens.stories.svelte
src/tokens/newsGradientTokens.stories.svelte
src/tokens/newtabFontTokens.stories.svelte
src/tokens/newtabGradientTokens.stories.svelte
src/tokens/searchFontTokens.stories.svelte
src/tokens/searchGradientTokens.stories.svelte

Prior to this PR, tokens that get overriden by other layers were not accurately being displayed in Storyook. See for example font tokens for `Browser`.

[Storybook]: ensures layer tokens are only loaded when viewing story

---

src/components/dialog/dialog.stories.svelte
src/components/dialog/dialog.svelte

This PR adds two CSS properties for customizing the backdrop:
- `--leo-dialog-backdrop-color` controls the color of the backdrop
- `--leo-dialog-backdrop-filter` controls the filter applied to the content behind the backdrop

[Dialog]: Make is possible to customize the backdrop

---

src/components/dialog/dialog.svelte

Putting `width: 100%` should cause the title to fill the available width now

[Dialog]: Allow title to fill width

---

examples/example-ui-react/src/App.tsx
src/components/svelte-web.ts

Due to the limitations of slots in Svelte, when slots are changed the component is remounted when slots are changed. We'll never get this perfect, but maintaining focus is very useful, and makes components much easier to use.

[Input]: Maintain focus when creating/destroying slots

---

src/components/input/input.svelte

Currently, if the left-icon is interactive, that will be focused before the input

[Input]: Make input first focused element

---

package-lock.json
package.json
src/scripts/gen-android-icons.ts
src/scripts/gen-skia-icons.ts
src/scripts/update-icons.ts
src/tokens/config.ts
src/tokens/transformTokens.ts
src/tokens/transformation/common/leoParser.ts
src/tokens/transformation/skia/colorToSkiaString.ts
src/tokens/transformation/skia/index.ts
tsconfig.json

This adds support for progressively converting tokens and scripts to Typescript via use of `tsx` (ts execute, similar to `ts-node` or `npx` but works with modules).
Unlike `ts-node`, `tsx` supports `esmodules`, so you can write typescript as normal!
Unlike `npx`, `tsx` supports typescript!
I was inspired by someone in brave-core asking whether we could start converting our scripts there to `tsx`
This allows us to progressively convert `.js` files to `.ts` - this should be super handy when messing around with stuff in `leoParser.js`

[Typescript]: Add typescript support to scripts/token parsing

---

src/tokens/transformation/tailwind/twShadows.ts

The fix in https://github.com/brave/leo/pull/699 was too greedy, so this
adds additional checks to ensure that the color function isn't double
wrapped.

[Tokens](Tailwind): Only wrap shadow colors in function if necessary

---

src/components/segmentedControl/segmentedControl.svelte

There was an issue that surfaced in wallet, where the segmented control had very low contrast. I checked and it was different from figma, so here's an update
- themable/10 for component background
- container/highlight for hover state

[SegmentedControl]: Update styles for pill background and hover background

---

src/components/alert/alert.stories.svelte
src/components/alert/alert.svelte

This fixes an issue which @simonhong encountered where hiding the icon still shows the spacing for it.

[Alert]: Fix the padding on the Alert when removing the icon

---

package-lock.json
package.json
src/components/svelte-react.ts

This was breaking Brave Talk
Installing the @types/react package isn't strictly necessary for this PR but I wasn't sure where they were coming from

[React]: Fix latest @types/react compile

---

src/components/controlItem/controlItem.svelte

[SegmentedControl]: ensure controlItem doesn't shrink past its contents

---

src/components/radioButton/radioButton.svelte

When in a Svelte consumer, sometimes it's easiest to use the `bind:value` technique instead of an `onChange` handler.

[RadioButton]: make onChange optional

---

examples/plain-html/index.html
src/components/navigation/navigation.svelte
src/components/navigation/navigationItem.svelte

I've used `anchor-positioning` for the animations, so they work without any JS. Because its a fairly new API I've left in a fallback with no animations.

[Navigation]: Add animations when changing between active nav items

---

.github/renovate.json

I was talking to @thypon about disabling dependabot updates for `/examples/example-ui-react` or setting them to automerge and thought, why not set it for a bunch of things we normally merge anyway. If anything breaks, the build in Nala should fail, which will prevent the automerge.
Interested in hearing some thoughts on this (and whether its a bad idea).
For context, this was my original message to @thypon:
> Hey, I have a question - we have an example project in https://github.com/brave/leo/tree/main/examples/example-ui-react. Its not published/deployed anywhere and is only really used as a test bed during development to see if the React bindings are working properly.
Would it be safe to reduce the frequency of the dependabot/rennovate PRs (or set up automerge in this folder) as there …

[Renovate]: Enable automerge for devDependencies, minor and patches

---

src/components/svelte-web.ts

@szilardszaloki has been migrating some components to LitElement and noticed that the `leo-icon` elements weren't working.
Our working theory is that `Lit` injects whitespace into its HTML elements (there's a slotted `\n`):
https://search.brave.com/search?q=litelement+adds+whitespace+to+webcomponents&source=desktop&summary=1&summary_og=f0f84d159a7ddd8a5ff175

[WebComponents]: Ignore pure whitespace nodes

---

CODEOWNERS

At the moment, apps (such as `rennovate-approve[bot]`) can't be specified as CODEOWNERs, which means automerge doesn't work, because the PR is only approved by a bot.
https://github.com/orgs/community/discussions/23064#discussioncomment-3238917
Talked to @thypon and we're going to try the solution from the above discussion (removing CODEOWNERs requirement for package.json and package-lock.json).

[Automerge]: Remove CODEOWNERs for package.json

---

src/components/label/label.svelte

Resolves https://github.com/brave/leo/issues/574
Update label styles to match Figma's latest version.
https://www.figma.com/design/g8Z0q6TMPYDq6zXh9Y7LWD/%F0%9F%8C%8E-Universal?m=auto&node-id=195-15172&t=YtEkhqaM1E4QR5ZC-1

Update label style to match figma

---

src/components/button/button.svelte

With the current configuration, a consumer can disable a button via either `<Button isDisabled={true}>` or `<Button disabled={true}>`. However, these can be in conflict, and if the consumer accidentally does something like `<Button isDisabled={true} disabled={false}>`, then the `disabled` value wins.
A more likely conflict is if the user sets `isLoading` to true, but has a different condition for `disabled` which is `false`:
```svelte
<Button isLoading={isFetching} disabled={shouldDisableButtons}>
```
This PR attempts to avoid this by not allowing the consumer provided `disabled` attribute to override the `disabled` state set by the `Button` component.

[Button]: prevent consumer from overriding disabled atttribute

---

src/components/alert/alert.stories.svelte
src/components/alert/alert.svelte
src/components/alert/alertCenter.svelte

If a title slot was provided and the mode wasn't set to full then the title would never show. Seems to me that the full mode is only for adjustments made to make the alert look good with a title - ~so this PR forces 'full' mode when a title is present (or hasTitle prop is true for when the framework can't have an optional slot!)~. After discussion with @aguscruiz this PR removes `mode="full"` (leaving only a single mode, and removing it) as it wasn't being used by any designs, and allows title without any mode restriction
This also adds a variant for 'notice' type, which is color-less and has smaller features.

**Breaking** [Alert] Introduce notice type, remove mode prop, and title slot will always show if it has content

---

src/scripts/icons/skiafy.js

brave-core build doesn't work with the latest version of Leo because one of the icons it references is using a quadratic path. This updates the .svg ==> .icon converter to support quadratic paths.
You can test the support by opening `leo_reading_list_add.icon` from main in https://skia-icon-editor.vercel.app/
Additionally, it should crash the build if we encounter more unknown commands, which should prevent us merging any new broken icons

[Icons]: Add support for quadratic icons

---

src/components/buttonMenu/buttonMenu.svelte

But we can also preventDefault to stop any parent default behavior we were attempting to fix

[ButtonMenu] onclick does need stopPropagation after all to stop the Menu being blurred and closing itself

---

src/components/alert/alert.stories.svelte
src/components/button/button.stories.svelte
src/components/buttonMenu/buttonMenu.stories.svelte
src/components/checkbox/checkbox.stories.svelte
src/components/collapse/collapse.stories.svelte
src/components/dialog/dialog.stories.svelte
src/components/dropdown/dropdown.stories.svelte
src/components/icon/icon.stories.svelte
src/components/input/input.stories.svelte
src/components/label/label.stories.svelte
src/components/link/link.stories.svelte
src/components/navdots/navdots.stories.svelte
src/components/navigation/navigation.stories.svelte
src/components/progress/progressBar.stories.svelte
src/components/progress/progressRing.stories.svelte
src/components/radioButton/radioButton.stories.svelte
src/components/segmentedControl/segmentedControl.stories.svelte
src/components/textarea/textarea.stories.svelte
src/components/toggle/toggle.stories.svelte
src/components/tooltip/tooltip.stories.svelte
src/tokens/browserFontTokens.stories.svelte
src/tokens/marketingFontTokens.stories.svelte
src/tokens/newsGradientTokens.stories.svelte
src/tokens/newtabFontTokens.stories.svelte
src/tokens/newtabGradientTokens.stories.svelte
src/tokens/searchFontTokens.stories.svelte
src/tokens/searchGradientTokens.stories.svelte
src/tokens/universalColorTokens.stories.svelte
src/tokens/universalFontTokens.stories.svelte
src/tokens/universalGradientTokens.stories.svelte

Storybook now expects an exported meta object at the module level, rather than a <Meta /> element. This change modifies the stories to adhere to the new pattern. In a couple cases the `name` attribute of a `<Story />` element needed to be changed to avoid attempted reuse of an identifier within the same context.

Avoid deprecated meta-tag pattern

---

src/components/radioButton/radioButton.svelte

This means the Label will have the same size as the HTMLCustomElement wrapper

[RadioButton]: Make Label fill host

---

src/components/dialog/dialog.svelte

NOTE: this purpose of this PR is _not_ to bring the Dialog component up to date with the latest in Figma, but rather to provide consumers a way of automatically switching between `mobile` and `normal` sizes via screen size.
- **[Dialog]: add customizable media queries for switching to mobile styles**
- **[Dialog]: change position of action buttons right aligned**
- **[Dialog]: scroll entire dialog instead of just .body**

[Dialog]: **BREAKING** Replace 'size' property with media query

---

package-lock.json
package.json

We can't bump "@sveltejs/vite-plugin-svelte" which pulls in esbuild because they have a dependency on Svelte5 (which breaks everything).
This is for a vulnerability in esbuild

[Deps]: Override esbuild version

---

src/components/dialog/dialog.svelte

For some reason, the dialog viewed on ipads tries to take up the entire screen.
| before | after |
| -- | -- |
| ![Simulator Screenshot - iPad (10th generation) - 2025-02-21 at 16 22 16](https://github.com/user-attachments/assets/0854cd60-3eb1-4bfa-984a-6c0eab1fe076) | ![Simulator Screenshot - iPad (10th generation) - 2025-02-21 at 16 22 35](https://github.com/user-attachments/assets/d77b92a3-f913-458e-8ba0-bbe0a29663c8) |

[Dialog]: ensure dialog doesn't unnecessarily fill screen height

---

src/components/checkbox/checkbox.svelte

This fixes this kind of overflow when the Checkbox is used inside a WebComponent:
After the fix:
(we already do this with the RadioButton)

[Checkbox]: Make control fill web component

---

src/components/alert/alert.svelte
src/components/dialog/dialog.svelte
src/components/icon/icon.svelte
src/components/menu/menu.svelte
src/components/segmentedControl/segmentedControl.svelte

Using :global without parentheses around the targeted selector seems to
be undocumented, and results in an error in some environments. See for
example https://svelte.dev/playground/568dfa21589d4854a86243373526127c?version=4.2.19

[Components]: Change instances of ':global selector' to ':global(selector)'

---

src/components/dialog/dialog.svelte

I have a situation in `brave-core` where I want to conditionally render some content in a dialog. I need to control this solely via CSS.
It works pretty well, except that the close event is fired on the dialog, even when it is `display: none`

[Dialog]: Don't fire close event when `display: none`

---

src/components/dialog/dialog.svelte

Sometimes this outline shows up when the dialog is triggered programmatically in webcomponents land.

[Dialog]: Remove outline

---

src/scripts/gen-types.js

`path.resolve` is relative to the package root, while `require.resolve` is relative to `node_modules`

[types]: Fix generated WebComponent types

---

tests/gen-types.test.ts

This adds a smoke test that types are being generated correctly. It's not part of #1065 because none of the jest tests are passing at the moment (and don't seem to run on CI) and that needs to land urgently
Blocked on https://github.com/brave/leo/pull/1067

[types]: Add test for gen-types

---

src/components/dialog/dialog.stories.svelte
src/components/input/input.svelte

Related tasks: https://github.com/brave/leo/issues/997
On the dialog, the tab order is incorrect when you have the close button turned on. In the case of the issue reported above (https://github.com/brave/leo/issues/997) the input field has the attribute `tabindex=1`,  and ~~adding the same `tabindex=1` to the close button keeps the order correct~~.
The bug is actually a side effect of adding `tabindex=1` to the Input field so tabbing works properly in a shadowroot for the input field. The fix here is to conditionally add tab index when the root node for the Input field is not the document.
- Conditionally adds `tabindex=1` attribute to the Input component when the root note is not the document
- Adds a storybook story for `Show Close`
- Adds an input field to the default Dialog component …

[Dialog]: Fix input field tab order

---

src/components/tooltip/tooltip.svelte

Additionally, the animation was never being played - you can test this by setting `fadeDuration` to `1000` in the storybook (no fade).
**Note:** Svelte `transitions` break JSDOM - we should avoid them.

[Tooltip]: Remove Svelte transition - it breaks jsdom in unittests

---

package-lock.json
package.json
src/scripts/update-icons.ts

I think this probably broke when we converted a bunch of stuff over to esmodules. I also noticed there was a timeout happening occasionally, so I increased the timeout to 10 minutes (there are some big API requests).

[Icons]: Fix update script

---

src/components/buttonMenu/buttonMenu.stories.svelte
src/components/buttonMenu/buttonMenu.svelte
src/components/menu/menu.svelte

In brave-core we have a few bits of UI where the Menu should anchor to the top! At the moment this is most coincidentally working because we're showing the menus at the bottom of the screen so they get flipped to show above (because there isn't enough space).
This exposes the properties.

[ButtonMenu]: Make placement configurable

---

src/components/formItem/formItem.svelte

I removed the color mix that was used for the default state of the form input. But I kept it on hover. It's still allowing me to customize the color if I change it to something else.

Remove color mix from default state of form item

---

src/components/floating/floating.svelte

Adjusted the distance between the dropdown elements and the parent so they're closed together.

adjust dropdown gap between parent and floating element

---

src/tokens/transformation/common/fontHelper.ts
src/tokens/transformation/tailwind/twFont.ts
src/tokens/transformation/web/webFont.ts

This PR moves the changes from https://github.com/brave/leo/pull/1158 to a helper module, and applies them to `twFont.ts` as well.

[Fonts]: transform tailwind fonts into system-ui fonts

---

src/components/dropdown/dropdown.stories.svelte
src/components/formItem/formItem.svelte
src/components/input/input.stories.svelte

- **[FormItem: Fix spacing**
- **[FormItem]: Add 'inline' mode**
The immediate use for this is the language switcher for account.brave.com.

[FormItem]: Add 'inline' mode

---

src/components/dropdown/dropdown.stories.svelte
src/components/dropdown/dropdown.svelte
src/components/formItem/formItem.svelte
src/components/input/input.stories.svelte

Crucially, this means that the mode will no longer set the display property on FormItem and Dropdown to `inline-flex`, leaving this behavior up to the consumer to set.

[FormItem]: Rename 'inline' mode to 'plain'

---

examples/plain-html/index.html
src/components/checkbox/checkbox.svelte

This seems to be because WebKit doesn't like having a `:has` selector in a `shadowRoot`, which is why the Storybook was working

[Checkbox]: Make checkbox WebComponent work on iOS

---

src/components/menu/menu.svelte

https://www.w3.org/TR/selectors-4/#the-nth-child-pseudo
(look for Example 49 for some explanation)
Basically, this selects:
A `leo-menu-item`/`leo-option` if:
1. Its the first child without a `slot` attribute
2. Its the last child without a `slot` attribute
This will fix (when merged) https://github.com/brave/brave-browser/issues/49013
FWIW, this feature is CSS baseline 2023, so should be all good for support!
https://caniuse.com/css-nth-child-of

[Menu]: Only consider non slotted elements when deciding if an item is first/last

---

src/components/menu/menu.svelte

When there was just a single item the bottom margin was overriding the top one. Solution is to set the top/bottom padding separately.

[ButtonMenu]: Fix margin for single item

---

src/tokens/transformation/tailwind/extractComponentStyles.js

Since objects can't have duplicate keys, the process of converting our CSS rules to JS objects resulted in `postcss-js` combining multiple `at-rules` into one, which resulted in improper ordering of queries and styles.

[Tailwind]: Prevent postcss-js from merging at-rules in extracted component styles
