- tokens/design-tokens.tokens.json
Updated font styles for desktop headings and there may be other small differences too
> Updated font styles for desktop headings

- tokens/design-tokens.tokens.json
- tokens/transformation/web/formatCss.js
- web-components/button/button.svelte
Updated font values and color values.
Renamed secondary to primary and viceversa. Also added a "primary-legacy", which is the blurple. New color is more blue-tinted.
Removed a lot of unused gradients and updated elevation values
> Big update on colors and font values

- .github/workflows/build.yml
Adds basic deploy script so that we can implement a super simple check for PRs to ensure that build works.
> adds build.yml workflow

- tokens/config.js
- tokens/transformTokens.js
- tokens/transformation/skia/index.js
- tokens/transformation/skia/templates/colors.h.template
This PR generate output for Skia colors in a single header file.
1. Removes "LightMode" and "DarkMode" from names
2. adds two specific namespaces
> Added Skia color config

- tokens/transformation/tailwind/formatCssColorVars.js
- tokens/transformation/web/formatCss.js
Reverts brave-experiments/leo#34
> Revert "Remove redundant declarations"

- package-lock.json
- package.json
- tokens/design-tokens.tokens.json
- tokens/legacy-colors.json
- tokens/transformation/common/leoParser.js
- tokens/transformation/tailwind/formatCssColorVars.js
- tokens/transformation/tailwind/formatTokens.js
- tokens/transformation/web/formatCss.js
- tokens/utils.js
- web-components/button/button.svelte
Created new contextual styles to coexist with the extended palette. Both with light/dark modes. Also reorganized text styles, separating the component specific ones to their own "Components" folder.
>  Design system overhaul

- tokens/transformation/common/leoParser.js
- web-components/button/button.svelte
> Group values for focus-state

- .storybook/global.svelte
- web-components/button/button.stories.svelte
- web-components/button/button.svelte
- web-components/button/props.ts
- web-components/button/react.ts
Depends on https://github.com/brave-experiments/leo/pull/37
> allows button to accept href and use anchor tag

- .storybook/main.js
- postcss/theme.js
- tests/theme.dark.test.js
- tests/theme.light.test.js
- tests/theme.mixed.test.js
- web-components/button/button.svelte
- fixes issues with postcss/theme plugin
- fixes hover color for button.isPrimary in dark mode
> Theme plugin fixes

- .github/workflows/build.yml
Related: https://github.com/brave/devops/issues/8494
> deprecate-set-output

- web-components/navdots/navdots.stories.svelte
- web-components/navdots/navdots.svelte
Fixes https://github.com/brave/leo/issues/65
Add navigation dots
[Screencast from 2022-11-28 12-34-57.webm](https://user-images.githubusercontent.com/7678024/204165735-52252112-89e6-4a8d-8176-6ed5e6d6f785.webm)
Storybook:
https://leo-storybook-git-wc-nav-dots-fallaciousreasoning.vercel.app/?path=/story/nav-dots--default
> [Component] Navdots

- examples/example-ui-react/src/App.tsx
- examples/example-ui-react/src/MySvelteComponent/react.ts
- web-components/collapse/collapse.stories.svelte
- web-components/collapse/collapse.svelte
Fixes https://github.com/brave/leo/issues/53
This adds a simple collapse component to Leo based on the UX mockup in [Figma](https://www.figma.com/file/g8Z0q6TMPYDq6zXh9Y7LWD/%F0%9F%8C%8E-Universal?node-id=278%3A12772)
Storybook:
https://leo-storybook-git-wc-collapse-fallaciousreasoning.vercel.app/
> [Component]: Collapse

- .github/workflows/build.yml
Fix https://github.com/brave/leo/issues/103
> Create PR deploys

- web-components/toggle/props.ts
- web-components/toggle/toggle.stories.svelte
- web-components/toggle/toggle.svelte
This PR implements a toggle component for Leo, fixing https://github.com/brave/leo/issues/61
A storybook is available here:
https://leo-storybook-git-wc-toggle-fallaciousreasoning.vercel.app/
> [Component] Toggle

- .github/workflows/build.yml
Resolves https://github.com/brave/leo/issues/103
> Deploy on push to main

- package-lock.json
- package.json
- tokens/config.js
- tokens/transformTokens.js
- tokens/transformation/styledComponents/formatStyledComponentsTheme.js
- tokens/transformation/styledComponents/index.js
Outputs a JSON object that maps key to css variable name
<details>
<summary>Preview the output</summary>
```ts
export default {
"spacing": {
"4": "var(--spacing-4)",
"8": "var(--spacing-8)",
"12": "var(--spacing-12)",
"16": "var(--spacing-16)",
"24": "var(--spacing-24)",
"32": "var(--spacing-32)",
"40": "var(--spacing-40)"
},
"radius": {
"1": "var(--radius-1)",
"2": "var(--radius-2)",
"4": "var(--radius-4)",
"8": "var(--radius-8)",
"12": "var(--radius-12)",
"16": "var(--radius-16)",
"full": "var(--radius-full)"
},
"color": {
"light": {
"text": {
"primary": "var(--color-light-text-primary)",
"secondary": "var(--color-light-text-secondary)",
"interactive": "var(--color-light-text-interactive)",
"disabled": "var(--color-light-text-disabled)"
},
"icon": {
"default": …
```
> Generate a styled-components theme

- examples/plain-html/index.html
- rollup.config.js
- src/components/progress/progress.stories.svelte
- src/components/progress/progressBar.svelte
- src/components/progress/progressRing.svelte
- src/scripts/gen-react-bindings.js
Fixes https://github.com/brave/leo/issues/67
Fixes https://github.com/brave/leo/issues/66
Adds a progress ring and a progress bar. In addition, this PR makes it possible to have multiple components in a single folder.
> [Component] Progress Elements

- .github/workflows/cleanup.yml
Resolves https://github.com/brave/devops/issues/8849
> Cleanup deployed prs

- src/components/link/link.stories.svelte
- src/components/link/link.svelte
Adds a Link component
Fixes #52
> [Component]: Link

- src/components/label/label.stories.svelte
- src/components/label/label.svelte
Adds a Label component
Fixes https://github.com/brave/leo/issues/63
~~**Note:** The hero color doesn't work because it requires #75~~
> [Component]: Label

- src/tokens/browser.tokens.json
Added a set of tokens for things directly related to the browser apps.
First PR is focused on colors for icons and hover/active items
> Added browser tokens file

- src/components/svelte-react.ts
Avoids typescript errors in https://github.com/brave/leo/pull/239
> svelte-react handles initial undefined case

- src/tokens/browser.tokens.json
- src/tokens/ios.tokens.json
- src/tokens/universal.tokens.json
Changed light/container/highlight value
Also made native adjustments for font values in iOS and Android.
Btw @AlanBreck the token file I had "design-tokens.tokens.json" should be replaced by "universal.tokens.json" I renamed it to match the library name. Hope that's ok
> Updated universal / ios / android tokens

- README.md
- src/components/README.md
Resolves https://github.com/brave/leo/issues/238
Adds instructions for creating new components.
> [Documentation]: Add component creation documentation

- examples/plain-html/index.html
- src/components/svelte-web.ts
This PR fixes a few issues that @petemill & @AlanBreck brought up in the original [PR](https://github.com/brave/leo/pull/239) which weren't fixed because we were in a hurry to land it.
> WebComponents Followup

- src/components/checkbox/checkbox.stories.svelte
- src/components/checkbox/checkbox.svelte
- src/components/icon/icon.svelte
Adds a checkbox component
Fixes https://github.com/brave/leo/issues/59
~~**Note:** The colors aren't finalized because we broke some of the icon color tokens recently see [thread](https://bravesoftware.slack.com/archives/C03A0MWJXP0/p1679932188389139) for detail~~
> [Component]: Checkbox

- .github/workflows/update-icons.yml
`grep` uses regex syntax not `glob` syntax :facepalm:, so this was never detecting any updates
> [Icons]: Fix update-icons.yml action

- .github/workflows/update-icons.yml
@kim0 sorry to hit you with so many of these - nearly at the bottom of the file so there can't be too many more things I've messed up :laughing: 
Turns out I'm absolutely hopeless at writing workflow files
> [Icons Update Script]: Stage path correctly

- .storybook/main.cjs
Upload our CSS variables to https://leo.bravesoftware.com/
This is a prerequisite for #314 
Being able to easily access the tokens on the current main branch will make generating diffs much easier.
> [Meta]: Upload CSS variables

- .github/workflows/build.yml
Fixes https://github.com/brave/leo/issues/128
This works via a couple of steps:
1. ~~Upload the `variables.css` file as part of the storybook. This means we can fetch the current tokens from https://leo.bravesoftware.com/css/variables.css~~ Done as part of #315 
2. Run a diff of that `variables.css` file and the current one
3. Upload it, as part of a details/summary, so we can see the diff on the PR.
> [Meta]: Provide diff of `variables.css`

- src/components/button/button.svelte
- src/components/dropdown/dropdown.stories.svelte
- src/components/dropdown/dropdown.svelte
- src/components/formItem/formItem.svelte
- src/components/label/label.stories.svelte
- src/components/label/label.svelte
[Label Updates] Fixes #289
[Outline Button Updates] Fixes #297
[New Dropdown Variants] Fixes #294
> Update components to match new designs

- src/components/collapse/collapse.stories.svelte
- src/components/collapse/collapse.svelte
Adds two new variables for controlling the padding of the collapse summary and content.
> [Collapse]: Add CSS variables for tweaking collapse padding

- src/components/button/button.stories.svelte
- src/components/button/button.svelte
Fixes https://github.com/brave/leo/issues/51
In addition:
- Adds new story for fab buttons
- Fixes the focus outline for the `plain-faint` variant (previously it was heavily rounded)
> [Component]: Floating action buttons

- src/components/collapse/collapse.stories.svelte
- src/components/collapse/collapse.svelte
This will allow more customization of how the title is displayed.
> [Collapse]: Add slot for title

- examples/plain-html/index.html
- src/components/dropdown/dropdown.stories.svelte
- src/components/formItem/formItem.svelte
- src/components/icon/icon.svelte
- src/components/input/input.stories.svelte
- src/components/input/input.svelte
Fixes https://github.com/brave/leo/issues/54
Closes #79
> [Component]: Input

- .github/workflows/update-icons.yml
Resolves https://github.com/brave/devops/issues/10381
> Add GPG for git commit signing

- .gitignore
- src/tokens/config.js
- src/tokens/transformTokens.js
- src/tokens/transformation/ios/colorsets.js
- src/tokens/transformation/ios/index.js
- src/tokens/transformation/ios/templates/ColorSetAccessors.swift.template
- src/tokens/transformation/ios/templates/Gradients.swift.template
This adds Swift code generation for the leo design system colours & gradients 
This will also resolve https://github.com/brave/leo/issues/378 as it includes the code to generate start/stop points for CSS angle-based gradients.
> Add iOS color & gradient Swift generation

- src/components/checkbox/checkbox.svelte
> Change Checkbox changed event to change

- src/components/icon/icon.svelte
- src/components/svelte-web.ts
- src/svelteDirectives/isSSR.ts
Allows Leo react components to work with an SSR application
> fix: prevent window methods being called when SSR

- src/components/alert/alert.stories.svelte
- src/components/alert/alertCenter.svelte
Resolves: https://github.com/brave/leo/issues/399
> Added user defined width to alert center

- .github/workflows/build.yml
Avoid double triggering (push & PR)
> Trigger build on push to main only

- .storybook/main.cjs
- .storybook/preview-head.html
- .storybook/preview.js
- package-lock.json
- package.json
- src/components/alert/alert.stories.svelte
- src/components/button/button.stories.svelte
- src/components/buttonMenu/buttonMenu.stories.svelte
- src/components/checkbox/checkbox.stories.svelte
- src/components/collapse/collapse.stories.svelte
- src/components/dialog/dialog.stories.svelte
- src/components/dropdown/dropdown.stories.svelte
- src/components/icon/icon.stories.svelte
- src/components/input/input.stories.svelte
- src/components/label/label.stories.svelte
- src/components/link/link.stories.svelte
- src/components/navdots/navdots.stories.svelte
- src/components/progress/progressBar.stories.svelte
- src/components/progress/progressRing.stories.svelte
- src/components/radioButton/radioButton.stories.svelte
- src/components/toggle/toggle.stories.svelte
- src/components/tooltip/tooltip.stories.svelte
- src/storyHelpers/ColorTokenSwatchGroup.svelte
- src/storyHelpers/Copiable.svelte
- src/storyHelpers/FontTokenSwatchGroup.svelte
- src/tokens/colorTokens.stories.svelte
- src/tokens/fontTokens.stories.svelte
- src/tokens/gradientTokens.stories.svelte
- src/tokens/transformation/common/leoParser.js
Partially resolves https://github.com/brave/leo/issues/351
- adds color tokens to storybook
- adds font tokens to storybook
- adds gradient tokens to storybook
Remaining:
- typography (?)
- effect
- spacing
- icon
- radius
> Token stories

- src/components/button/button.svelte
Fixes https://github.com/brave/leo/issues/422
> [Button]: Update padding on tiny variant

- src/components/menu/menu.svelte
Fixes https://github.com/brave/leo/issues/425
This was impacting @nullhook
> [Dropdown]: Look at `.value` property as well as attribute when determining value.

- src/components/icon/icon.svelte
- src/components/link/link.svelte
- adds type to argument for preloadIcon fn
- removes 'all: unset' from Link component
> Minor fixes

- src/tokens/variables.tokens.json
Update variables from Figma using https://github.com/fallaciousreasoning/figma-exporter
> [Variables]: Update from Figma

- src/components/button/button.stories.svelte
- src/components/button/button.svelte
AI Chat needs this, as it has some non-standard sized buttons. @petemill I think this is some worthwhile customization.
> [Button]: Adds a CSS variable for controlling the button radius

- src/components/dialog/dialog.svelte
> [Dialog]: Conditionally render title row

- src/tokens/transformation/web/formatCssAsJs.js
Especially with spacing tokens, this makes it much easier to tell what you're using
Spacing:
Color:
> Token comments

- src/components/toggle/toggle.svelte
Fixes https://github.com/brave/leo/issues/516
> [Component]: Toggle - Design Updates

- src/components/label/label.stories.svelte
- src/components/label/label.svelte
Resolves https://github.com/brave/leo/issues/522
> **BREAKING** [Label]: adds two icon slots to Label to enforce proper spacing

- .storybook/global.svelte
This uses @AlanBreck's cool `SegmentedControl`
> [Storybook]: Allow using the system theme

- src/components/formItem/formItem.svelte
I need this for the searchbox on the NTP
> [FormControl]: Make focus state customizable

- src/components/button/button.svelte
- src/components/controlItem/controlItem.svelte
- src/components/formItem/formItem.svelte
- src/components/segmentedControl/segmentedControl.svelte
- src/tokens/universal.tokens.json
Resolves https://github.com/brave/leo/issues/510
Resolves https://github.com/brave/leo/issues/511
Resolves https://github.com/brave/leo/issues/528
Resolves #567
Resolves #514
NOTE: this should be rebased and not squashed.
> Updates components to rounded rectangle style

- src/storyHelpers/Copiable.svelte
- src/storyHelpers/FontTokenSwatchGroup.svelte
- src/tokens/transformation/web/formatCssAsJs.js
- src/tokens/utils.js
- **[Tokens]: improves token name segment removal**
- **[Storybook]: fixes font token rendering**
> misc fixes

- src/tokens/transformation/android/formats/fontStyle.js
Resolves https://github.com/brave/leo/issues/646
> Update android style

- src/storyHelpers/ColorTokenSwatchGroup.svelte
- src/storyHelpers/ConditionalSwatchGroup.svelte
Required for https://github.com/brave/leo/pull/543
> [Storybook]: fixes color/gradient swatch rendering

- src/components/buttonMenu/buttonMenu.svelte
@AlanBreck we should find a way to specify that props should be forwarded :laughing:
> [ButtonMenu]: Make it possible to set the positionStrategy for ButtonMenu

- src/components/button/button.svelte
- **[Button]: removes background from plain-faint fab**
- **[Button]: prevents button content from shrinking**
> Button fixes

- src/tokens/transformation/web/formattedVariables.js
sort tokens by name, so that the diffs are more helpful
> [Tokens]: More stable output for diffs

- src/components/formItem/formItem.svelte
We need this for the NTP search box
> [FormItem]: Make text color configurable

- src/components/toggle/toggle.svelte
@emerick reported that the Toggles sometimes change when he right clicks them. This should fix that
> [Toggle]: Don't drag on right click

- src/components/button/button.svelte
Fixes https://github.com/brave/leo/issues/690
> [Button]: Make empty string truthy in HTML attributes

- src/components/toggle/toggle.stories.svelte
- src/components/toggle/toggle.svelte
Fixes https://github.com/brave/leo/issues/681
I also reduced the transition duration as it felt a bit sluggish. @aguscruiz to a professional opinion.
> [Toggle]: Shorten animation, remove shadow

- src/components/button/button.svelte
Need to update Button Props to resolve event type onClick for this issue:
https://github.com/brave/brave-browser/issues/36550
> fix: provided type for button onClick prop

- src/components/dropdown/dropdown.stories.svelte
- src/components/menu/menu.svelte
I updated the padding of the items inside the dropdown, also the border radius and spacing between elements.
> [Dropdown]: Update spacing and padding of dropdown options

- src/components/dialog/dialog.svelte
- Added border to non-modal dialogs
- Changed elevation of non-modal dialog
> Updated border and elevation on dialog

- src/components/formItem/formItem.svelte
Added a transition for box shadow and border in inputs
> Added a quick animation for hover state in inputs

- src/tokens/universal.variables.json
Fixes https://github.com/brave/leo/issues/753
> [Tokens]: Fix dark/light default values

- src/tokens/universal.tokens.json
- src/tokens/universal.variables.json
Latest style set from Figma
- Font styles
- Shadow colors
> [Tokens] Updated styles file for universal

- examples/plain-html/index.html
- src/components/controlItem/controlItem.svelte
- src/components/segmentedControl/segmentedControl.stories.svelte
- src/components/segmentedControl/segmentedControl.svelte
...additionally ensures that control items will be evenly split across
the entire width.
> [SegmentedControl]: Add var to control max width

- src/tokens/transformation/common/leoParser.ts
- src/tokens/transformation/tailwind/formatTokens.ts
- src/tokens/universal.tokens.json
- src/tokens/universal.variables.json
Updates
universal.tokens.json
universal.variables.json
> Update of our tokens and variables to the latest values

- src/tokens/universal.variables.json
This updated set of variables is aimed to correct the default dark mode theme and match what we currently have on the browser. Making it darker than Chromium's default dark mode
> Update for desktop dark mode colors in tri-color themes

- src/components/button/button.svelte
Resolves https://github.com/brave/leo/issues/730
> [Button]: Update styling for various states

- src/components/navigation/navigationItem.svelte
This will allow consumers to pass in custom icons (ie. an inline svg)
helps with https://github.com/brave/leo/issues/847
> [Navigation]: Make it possible to set the icon via a slot

- .github/workflows/audit-deps.yml
Prerequisite for https://github.com/brave/leo/pull/837
> [DevOps]: Add builder to audit dependencies

- src/components/formItem/formItem.svelte
@aguscruiz wants us to remove it on the SearchBox on the NTP
> [FormItem]: Make it possible to customize border color

- src/components/dialog/dialog.svelte
| Before | After |
| -- | -- |
| <img width="531" alt="Screenshot 2024-11-25 at 9 47 22 PM" src="https://github.com/user-attachments/assets/f9f3890a-2e94-4060-902d-680892760288"> | <img width="531" alt="Screenshot 2024-11-25 at 9 48 04 PM" src="https://github.com/user-attachments/assets/6aaaecff-c0ca-4af6-9cd3-db3c289a2a1a"> |
> [Dialog]: change close button to fab

- src/components/buttonMenu/buttonMenu.stories.svelte
- src/components/buttonMenu/buttonMenu.svelte
> [ButtonMenu]: Fix uncontrolled close handler

- src/components/textarea/textarea.stories.svelte
- src/components/textarea/textarea.svelte
Resolves https://github.com/brave/leo/issues/362
> Introduces support for a multiline component

- src/components/alert/alert.stories.svelte
- src/components/alert/alertCenter.svelte
Resolves https://github.com/brave/leo/issues/932
> [AlertCenter]: fixes 'undefined' title when no title provided

- src/components/checkbox/checkbox.svelte
I've got a SSR PR and I noticed the checkbox doesn't work without JavaScript enabled
> [SSR]: Make checkbox work without JavaScript

- src/components/button/button.svelte
Fix on % for outline calculation so it's closer to Figma
> update value for outline button outline

- package-lock.json
- package.json
We forgot to bump the override version here
> [Axios]: Bump to latest

- package-lock.json
- package.json
fix https://github.com/brave/leo/security/dependabot/119
> fix vite dependabot issue

- .github/workflows/audit-deps.yml
- .github/workflows/build.yml
> fix: autopin dependencies

- src/tokens/universalFontTokens.stories.svelte
Resolves https://github.com/brave/leo/issues/1049
> [Storybook]: Remove nonexistent story for universal fonts

- src/tokens/universal.variables.json
@aguscruiz has tweaked the color tokens. We should update this in brave-core
> [Tokens]: Update variables

- .github/workflows/build.yml
- tests/theme.dark.test.js
- tests/theme.light.test.js
- tests/theme.mixed.test.js
- tests/tokens.js.test.js
tests were failing because they aren't run on CI so when we changed defaults/formatting the tests silently started failing
> [ci]: Fix tests and run them as part of the build on CI

- src/tokens/universal.variables.json
Update colors for material tokens
> [Tokens]: Update universal colors from Figma

- src/components/alert/alert.stories.svelte
- src/components/alert/alert.svelte
Updated the spacing between buttons in alerts
> Alert minor fix

- src/components/tooltip/tooltip.svelte
We're going to add some delays before opening in a few tooltip heavy places in AI Chat
> [Tooltip]: Configurable delay before opening

- src/components/tooltip/tooltip.stories.svelte
- src/components/tooltip/tooltip.svelte
Adjusted styles to make them look like Figma.
https://www.figma.com/design/g8Z0q6TMPYDq6zXh9Y7LWD/%F0%9F%8C%8E-Universal?m=auto&node-id=5253-22436&t=RFDwM4hgq1Xf3pBh-1
> Tooltip mini fixes

- src/components/formItem/formItem.svelte
- src/components/input/input.svelte
| Before | After |
|--------|--------|
| <img width="1049" height="257" alt="Screenshot 2025-08-25 at 10 13 52 PM" src="https://github.com/user-attachments/assets/477973dc-2661-4349-8646-ab9fb24fdba9" /> | <img width="1032" height="254" alt="Screenshot 2025-08-25 at 10 16 01 PM" src="https://github.com/user-attachments/assets/e2975510-8c61-4c40-a29a-b029b92f03d3" /> | 
Introduced by https://github.com/brave/leo/commit/4924dde3bf6d1f9f458a7335a3e883b349e4e635
> [FormItem]: Fix layout bug introduced by '[FormItem: Fix spacing'

- src/components/dialog/dialog.svelte
See https://github.com/brave/brave-browser/issues/49439#issuecomment-3312255528 for issue in brave-core
> [Dialog]: Show close button above  header
